#cache
cacheServerName=http://localhost:8886/cache/
#datasource
datasourceServerName=http://localhost:8889/datasource/
#shiro LoginUrl
loginUrl=/a/login
#shiro Logout
logout=/a/logout
#shiro FilterMap
FilterMapJwt=/a/**,/datasource/**,/cache/**
#shiro FilterMapAnon
FilterMapAnon=/a/app/fileDownloadThumbNew,\
              /a/createCharacter,/a/showValidateCode,/a/dynamic/zform/expdata,/a/dynamic/zform/impdata,\
              /a/getLdapSwitch,\
              /a/dynamic/zform/getZformMapView,/a/dynamic/zform/datamapView/*,\
              /a/sys/dict/getDictListView2,\
              /a/sys/tagTree/areaSubTree,\
              /a/wx/jsCodeToOpenId,\
              /a/onlyoffice/*,/a/system/sysFile/fileDownload,\
              /a/getLoginPublicKey,/a/getTdtKey
#shiro file FilterMapAnon
FilterFileMapToken=/a/system/sysFile/fileDownload


