export  default {
    symbolData:{
        "commonUse":[
            {id:"1", value:"Na⁺"},
            {id:"2", value:"NH4⁺"},
            {id:"3", value:"K⁺"},
            {id:"4", value:"Mg²⁺"},
            {id:"5", value:"Ca²⁺"},
            {id:"6", value:"SO₂"},
            {id:"7", value:"NO"},
            {id:"8", value:"NO₂"},
            {id:"9", value:"CO"},
            {id:"10", value:"CO₂"},
            {id:"11", value:"BOD₅"},
            {id:"12", value:"Fˉ"},
            {id:"13", value:"Clˉ"},
            {id:"14", value:"NO₂ˉ"},
            {id:"15", value:"Brˉ"},
            {id:"16", value:"NO₃ˉ"},
            {id:"17", value:"PO₄³ˉ"},
            {id:"18", value:"SO₃²ˉ"},
            {id:"19", value:"SO₄²ˉ"},
            {id:"20", value:"Li⁺"},
            {id:"21", value:"O³"},
            {id:"22", value:"PM₁₀"},
            {id:"23", value:"PM₂.₅"},
            {id:"24", value:"¹⁴C"},
            {id:"25", value:"C₆"},
            {id:"26", value:"C₉"},
            {id:"27", value:"C₁₀"},
            {id:"28", value:"C₄₀"},
            {id:"29", value:"O₂"},
            {id:"30", value:"PCBₛ"},
            {id:"31", value:"PAHₛ"},
            {id:"32", value:"BOD₂"},
            {id:"33", value:"Eᵦmax"}, /*没找到max下标*/
            // {id:"34", value:"3,5-Br₂-PADAP"},
        ],
        "subIndex":[
            {id:"1",value:"⁰"},
            {id:"2",value:"¹"},
            {id:"3",value:"²"},
            {id:"4",value:"³"},
            {id:"5",value:"⁴"},
            {id:"6",value:"⁵"},
            {id:"7",value:"⁶"},
            {id:"8",value:"⁷"},
            {id:"9",value:"⁸"},
            {id:"10",value:"⁹"},
            {id:"11",value:"ᴬ"},
            {id:"12",value:"ᴮ"},
            {id:"13",value:"ᴰ"},
            {id:"14",value:"ᴱ"},
            {id:"15",value:"ᴳ"},
            {id:"16",value:"ᴴ"},
            {id:"17",value:"ᴵ"},
            {id:"18",value:"ᴶ"},
            {id:"19",value:"ᴷ"},
            {id:"20",value:"ᴸ"},
            {id:"21",value:"ᴹ"},
            {id:"22",value:"ᴺ"},
            {id:"23",value:"ᴼ"},
            {id:"24",value:"ᴾ"},
            {id:"25",value:"ᴿ"},
            {id:"26",value:"ᵀ"},
            {id:"27",value:"ᵁ"},
            {id:"28",value:"ᵂ"},
            {id:"29",value:"ᵃ"},
            {id:"30",value:"ᵇ"},
            {id:"31",value:"ᶜ"},
            {id:"32",value:"ᵈ"},
            {id:"33",value:"ᵉ"},
            {id:"34",value:"ᶠ"},
            {id:"35",value:"ᵍ"},
            {id:"36",value:"ʰ"},
            {id:"37",value:"ⁱ"},
            {id:"38",value:"ʲ"},
            {id:"39",value:"ᵏ"},
            {id:"40",value:"ˡ"},
            {id:"41",value:"ᵐ"},
            {id:"42",value:"ⁿ"},
            {id:"43",value:"ᵒ"},
            {id:"44",value:"ᵖ"},
            {id:"45",value:"ʳ"},
            {id:"46",value:"ˢ"},
            {id:"47",value:"ᵗ"},
            {id:"48",value:"ᵘ"},
            {id:"49",value:"ᵛ"},
            {id:"50",value:"ʷ"},
            {id:"51",value:"ˣ"},
            {id:"52",value:"ʸ"},
            {id:"53",value:"ᶻ"},
            {id:"54",value:"⁺"},
            {id:"55",value:"⁻"},
            {id:"56",value:"⁼"},
            {id:"57",value:"℡"},
            {id:"58",value:"™"},
            {id:"59",value:"⁽"},
            {id:"60",value:"⁾"}
        ],"topIndex": [
            { "id": "1", "value": "₀" },
            { "id": "2", "value": "₁" },
            { "id": "3", "value": "₂" },
            { "id": "4", "value": "₃" },
            { "id": "5", "value": "₄" },
            { "id": "6", "value": "₅" },
            { "id": "7", "value": "₆" },
            { "id": "8", "value": "₇" },
            { "id": "9", "value": "₈" },
            { "id": "10", "value": "₉" },
            { "id": "11", "value": "ₐ" },
            { "id": "12", "value": "ₑ" },
            { "id": "13", "value": "ᵢ" },
            { "id": "14", "value": "ₒ" },
            { "id": "15", "value": "ᵣ" },
            { "id": "16", "value": "ᵤ" },
            { "id": "17", "value": "ᵥ" },
            { "id": "18", "value": "ₓ" },
            { "id": "19", "value": "₊" },
            { "id": "20", "value": "₋" },
            { "id": "21", "value": "₌" },
            { "id": "22", "value": "₍" },
            { "id": "23", "value": "₎" }
        ],
        "serialNumber": [
            {"id":"1", "value":"①"},
            {"id":"2", "value":"②"},
            {"id":"3", "value":"③"},
            {"id":"4", "value":"④"},
            {"id":"5", "value":"⑤"},
            {"id":"6", "value":"⑥"},
            {"id":"7", "value":"⑦"},
            {"id":"8", "value":"⑧"},
            {"id":"9", "value":"⑩"},
            {"id":"10", "value":"⑪"},
            {"id":"11", "value":"⑬"},
            {"id":"12", "value":"⑭"},
            {"id":"13", "value":"⑮"}
        ],
        "unit":[
            {"id":"1", "value":"Ω"},
            {"id":"2", "value":"℃"},
            {"id":"3", "value":"%"},
            {"id":"4", "value":"‰"},
            {"id":"5", "value":"℉"},
            {"id":"6", "value":"㎎"},
            {"id":"7", "value":"㎏"},
            {"id":"8", "value":"μm"},
            {"id":"9", "value":"㎜"},
            {"id":"10", "value":"㎞"},
            {"id":"11", "value":"㎡"},
            {"id":"12", "value":"m³"},
            {"id":"13", "value":"㏄"},
            {"id":"14", "value":"ml"},
            {"id":"15", "value":"mol"},
            {"id":"16", "value":"㏕"},
        ],
        "romanSymbols":[
            {id:"1",value:"Ⅰ"},
            {id:"2",value:"Ⅱ"},
            {id:"3",value:"Ⅲ"},
            {id:"4",value:"Ⅳ"},
            {id:"5",value:"Ⅴ"},
            {id:"6",value:"Ⅵ"},
            {id:"7",value:"Ⅶ"},
            {id:"8",value:"Ⅷ"},
            {id:"9",value:"Ⅸ"},
            {id:"10",value:"Ⅹ"},
            {id:"11",value:"Ⅺ"},
            {id:"12",value:"Ⅻ"}
        ],
        "mathSymbols":[
            {id:"1",value:"﹢"},
            {id:"2",value:"﹣"},
            {id:"3",value:"·"},
            {id:"4",value:"/"},
            {id:"5",value:"="},
            {id:"6",value:"﹤"},
            {id:"7",value:"﹥"},
            {id:"8",value:"≦"},
            {id:"9",value:"≧"},
            {id:"10",value:"≮"},
            {id:"11",value:"≯"},
            {id:"12",value:"≡"},
            {id:"13",value:"＋"},
            {id:"14",value:"－"},
            {id:"15",value:"×"},
            {id:"16",value:"÷"},
            {id:"17",value:"＝"},
            {id:"18",value:"＜"},
            {id:"19",value:"＞"},
            {id:"20",value:"≤"},
            {id:"21",value:"≥"},
            {id:"22",value:"≈"},
            {id:"23",value:"≒"},
            {id:"24",value:"≠"},
            {id:"25",value:"±"},
            {id:"26",value:"∶"},
            {id:"27",value:"∵"},
            {id:"28",value:"∴"},
            {id:"29",value:"∷"},
            {id:"30",value:"㏒"},
            {id:"31",value:"㏑"},
            {id:"32",value:"∑"},
            {id:"33",value:"∏"},
            {id:"34",value:"∅"},
            {id:"35",value:"℆"},
            {id:"36",value:"℅"},
            {id:"37",value:"℀"},
            {id:"38",value:"℁"},
            {id:"39",value:"⅍"},
            {id:"40",value:"⅟"},
            {id:"41",value:"⅞"},
            {id:"42",value:"⅝"},
            {id:"43",value:"⅜"},
            {id:"44",value:"⅛"},
            {id:"45",value:"⅚"},
            {id:"46",value:"⅙"},
            {id:"47",value:"⅘"},
            {id:"48",value:"⅗"},
            {id:"49",value:"⅖"},
            {id:"50",value:"⅕"},
            {id:"51",value:"¾"},
            {id:"52",value:"¼"},
            {id:"53",value:"⅔"},
            {id:"54",value:"⅓"},
            {id:"55",value:"½"},
            {id:"56",value:"i∫"},
            {id:"57",value:"∬"},
            {id:"58",value:"∭"},
            {id:"59",value:"∮"},
            {id:"60",value:"∯"},
            {id:"61",value:"∰"}
        ],
        "specialSymbols":[
            {id:"1", value:"°"},
            {id:"2", value:"%"},
            {id:"3", value:"‰"},
            {id:"4", value:"®"},
            {id:"5", value:"©"},
            {id:"6", value:"¢"},
            {id:"7", value:"℗"},
            {id:"8", value:"〒"},
            {id:"9", value:"☑"},
            {id:"10", value:"☒"},
            {id:"11", value:"☐"},
            {id:"12", value:"＆"},
            {id:"13", value:"＠"},
            {id:"14", value:"＃"},
            {id:"15", value:"……"},
            {id:"16", value:"～"},
            {id:"17", value:"ƒ"}
        ],
        "chineseCharacter":[
            {id:"1", value:"夻"},
            {id:"2", value:"㳕"},
            {id:"3", value:"荍"},
            {id:"4", value:"邨"},
            {id:"5", value:"聥"},
            {id:"6", value:"䓛"},
            {id:"7", value:"阚"},
            {id:"8", value:"崝"},
            {id:"9", value:"焗"},
            {id:"10", value:"漹"},
            {id:"11", value:"䢺"},
            {id:"12", value:"甦"},
            {id:"13", value:"耞"},
            {id:"14", value:"舲"},
            {id:"15", value:"燆"},
            {id:"16", value:"荄"},
            {id:"17", value:"皞"},
            {id:"18", value:"滘"},
            {id:"19", value:"僰"},
            {id:"20", value:"袆"},
            {id:"21", value:"芶"},
            {id:"22", value:"塍"},
            {id:"23", value:"漷"},
            {id:"24", value:"肸"},
            {id:"25", value:"㘵"}
        ],
        "greekAlphabet":[
            {id:"1", value:"Α"},
            {id:"2", value:"α"},
            {id:"3", value:"Β"},
            {id:"4", value:"β"},
            {id:"5", value:"Γ"},
            {id:"6", value:"γ"},
            {id:"7", value:"Δ"},
            {id:"8", value:"δ"},
            {id:"9", value:"Ε"},
            {id:"10", value:"ε"},
            {id:"11", value:"Ζ"},
            {id:"12", value:"ζ"},
            {id:"13", value:"Η"},
            {id:"14", value:"η"},
            {id:"15", value:"Θ"},
            {id:"16", value:"θ"},
            {id:"17", value:"Ι"},
            {id:"18", value:"ι"},
            {id:"19", value:"Κ"},
            {id:"20", value:"κ"},
            {id:"21", value:"Λ"},
            {id:"22", value:"λ"},
            {id:"23", value:"Μ"},
            {id:"24", value:"μ"},
            {id:"25", value:"Ν"},
            {id:"26", value:"ν"},
            {id:"27", value:"Ξ"},
            {id:"28", value:"ξ"},
            {id:"29", value:"Ο"},
            {id:"30", value:"ο"},
            {id:"31", value:"Π"},
            {id:"32", value:"π"},
            {id:"33", value:"Ρ"},
            {id:"34", value:"ρ"},
            {id:"35", value:"Σ"},
            {id:"36", value:"σ"},
            {id:"37", value:"Τ"},
            {id:"38", value:"τ"},
            {id:"39", value:"Υ"},
            {id:"40", value:"υ"},
            {id:"41", value:"Φ"},
            {id:"42", value:"φ"},
            {id:"43", value:"Χ"},
            {id:"44", value:"χ"},
            {id:"45", value:"Ψ"},
            {id:"46", value:"ψ"},
            {id:"47", value:"Ω"},
            {id:"48", value:"ω"}
        ],
    }

}